apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main
  namespace: monitoring
spec:
  rules:
  - host: alertmanager.minikube
    http:
      paths:
      - backend:
          service:
            name: alertmanager-main
            port: web
        path: /
        pathType: Prefix
